name: today
description: Today app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  
  # Auth
  crypto: ^3.0.3
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # Network Database
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Push Notifications
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2

  # UI
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  easy_image_viewer: ^1.5.0
  flutter_card_swiper: ^7.0.1
  flutter_picker_plus: ^1.1.3
  custom_sliding_segmented_control: ^1.8.3
  
  # System
  intl: ^0.19.0
  sizer: ^2.0.15
  telegram: ^0.0.3
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  flutter_app_badger: ^1.5.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
 
  # States
  bloc: ^8.1.4
  meta: ^1.12.0
  provider: ^6.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  path_provider: ^2.1.3

  # Local Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # Analytics
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/png/logo.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/png/
     - assets/svg/
     - fonts/

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
    - family: MontserratLight
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: MontserratThin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: TabIcons
      fonts:
        - asset: fonts/icons/TabIcons.ttf

flutter_native_splash:
  background_image: "assets/png/background.png"
  image: assets/png/brand.png
  background_image_dark: "assets/png/background.png"
  image_dark: assets/png/brand.png
  android_12:
    image: assets/png/brand_android12.png

  ios: false
  web: false

flutter_intl:
  enabled: true
