name: today
description: Dating app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  
  bloc: ^8.1.2
  intl: ^0.17.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.7.2
  url_launcher: ^6.1.11
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.0
  adaptive_theme: ^3.2.1
  cupertino_icons: ^1.0.2
  sign_in_with_apple: ^5.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/png/logo.png'

flutter:
  uses-material-design: true

  assets:
     - assets/png/
     - assets/svg/
     - fonts/

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
    - family: MontserratLight
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: MontserratThin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: TabIcons
      fonts:
        - asset: fonts/icons/TabIcons.ttf

flutter_native_splash:
  background_image: "assets/png/background.png"
  image: assets/png/brand.png
  background_image_dark: "assets/png/background.png"
  image_dark: assets/png/brand.png

  android_12:
    image: assets/png/brand_android12.png

  ios: false
  web: false

flutter_intl:
  enabled: true
