name: today
description: Dating app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  
  bloc: ^8.1.2
  hive: ^2.2.3
  meta: ^1.9.1
  intl: ^0.18.1
  crypto: ^3.0.3
  telegram: ^0.0.3
  provider: ^6.0.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  flutter_picker: ^2.1.0
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.6
  flutter_app_badger: ^1.5.0
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^5.0.0
  flutter_card_swiper: ^6.0.0
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  custom_sliding_segmented_control: ^1.7.5

  # Firebase Services
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.2.8
  firebase_analytics: ^10.5.1
  firebase_messaging: ^14.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/png/logo.png'

flutter:
  uses-material-design: true

  assets:
     - assets/png/
     - assets/svg/
     - fonts/

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
    - family: MontserratLight
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: MontserratThin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: TabIcons
      fonts:
        - asset: fonts/icons/TabIcons.ttf

flutter_native_splash:
  background_image: "assets/png/background.png"
  image: assets/png/brand.png
  background_image_dark: "assets/png/background.png"
  image_dark: assets/png/brand.png

  android_12:
    image: assets/png/brand_android12.png

  ios: false
  web: false

flutter_intl:
  enabled: true
